### ISSUE TITLE
Keep Reading

### ISSUE THREAD

**Issue by apatankars** [BPR-Web-Board/BPR-Site#76]
# Implement Keep Reading Component

## Overview
Create a reusable "Keep Reading" component that displays a grid of article previews with proper typography, responsive design, and integration with the existing WordPress data layer.

### Design Requirements
- **Title**: Large "Keep Reading" heading using serif font
- **Layout**: Responsive grid layout (1 column mobile, 2 columns tablet, 4 columns desktop)
- **Article Previews**: Each preview should include:
  - Placeholder image (gray background when no featured media)
  - Article title/headline
  - Author byline with "BY [AUTHOR NAME]" format
  - Optional excerpt text (truncated)

### Typography (from globals.css)
- **Section Title**: 
  - Font: `var(--font-primary-serif)` ("Nicholas" with Playfair Display fallback)
  - Size: `var(--font-size-lg)` (mobile), `var(--font-size-xl)` (tablet+)
  - Weight: 600 (semibold)
- **Article Titles**: 
  - Font: `var(--font-primary-serif)`
  - Size: `var(--font-size-sm)` (mobile), `var(--font-size-md)` (tablet+)
  - Weight: 600
- **Bylines**: 
  - Font: `var(--font-primary-sans)` ("FranklinGothic URW" with Libre Franklin fallback)
  - Size: `var(--font-size-xs)`
  - Weight: 500
  - Transform: uppercase
  - Letter-spacing: 0.06em
- **Excerpts**: 
  - Font: `var(--font-primary-text)` ("FreightText Pro" with Crimson Text fallback)
  - Size: `var(--font-size-xs)`
  - Color: `var(--color-dark-gray)`

### Color System (from globals.css)
- Background: `var(--color-white)` (#fffefa)
- Text: `var(--color-black)` (#0d0b00)
- Bylines: `var(--color-dark-gray)` (#3f3f3c)
- Excerpts: `var(--color-dark-gray)` (#3f3f3c)
- Image placeholder: `var(--color-light-gray)` (#f0efea)

### 1. Component Structure
Create the following files:
- `src/app/components/KeepReading/KeepReading.tsx`
- `src/app/components/KeepReading/KeepReading.css`
- `src/app/components/KeepReading/index.ts`

### 2. Props Interface
```typescript
interface KeepReadingProps {
  posts: EnhancedPost[];
  title?: string; // Default to "Keep Reading"
  maxPosts?: number; // Default to 8
  showExcerpts?: boolean; // Default to true
  className?: string;
}
```

### 3. Data Types
Use existing types from `lib/types.d.ts` and `lib/enhanced-wordpress.ts`:
- `EnhancedPost` for article data
- `Author` for author information
- `FeaturedMedia` for images

### 4. Responsive Grid Layout
- **Mobile** (< 768px): 1 column, full width
- **Tablet** (768px - 1023px): 2 columns
- **Desktop** (1024px+): 4 columns
- Gap between items: `var(--space-4)` (24px)

### 5. Image Handling
- Use Next.js `Image` component for featured media
- Implement `ImagePlaceholder` component (already exists) for posts without featured media
- Aspect ratio: 16:9 for consistency
- Image sizing: responsive with proper `sizes` attribute

### 6. Article Preview Component
Create a sub-component `KeepReadingArticlePreview` with:
- Link wrapper to article page (`/[section]/article/[slug]`)
- Hover states for interactive elements
- Proper semantic HTML (article, h3, time, etc.)
- Accessibility attributes (alt text, aria-labels)

### 1. WordPress Data Integration
- Use `getEnhancedPosts()` from `lib/enhanced-wordpress.ts`
- Handle loading states appropriately
- Implement error boundaries for failed API calls

### 2. URL Structure
- Link format: `/united-states/article/[slug]` or `/world/article/[slug]`
- Determine section from post categories or metadata
- Use Next.js `Link` component for client-side navigation

### 3. Author Information
- Display author name from `EnhancedPost.author_name` or `EnhancedPost.author_obj.name`
- Handle co-authors if present
- Default to "STAFF WRITER" if no author available

### 1. Base Styles (Mobile)
```css
.keep-reading {
  width: 100%;
  padding: var(--space-5) var(--space-3);
  background-color: var(--color-white);
}

.keep-reading-title {
  font-family: var(--font-primary-serif);
  font-size: var(--font-size-lg);
  font-weight: 600;
  margin-bottom: var(--space-5);
  color: var(--color-black);
}

.keep-reading-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: var(--space-4);
}

.article-preview {
  display: flex;
  flex-direction: column;
}

.article-image {
  width: 100%;
  aspect-ratio: 16/9;
  margin-bottom: var(--space-3);
  background-color: var(--color-light-gray);
}
```

### 2. Responsive Breakpoints
```css
@media (min-width: 768px) {
  .keep-reading-grid {
    grid-template-columns: repeat(2, 1fr);
  }
  
  .keep-reading-title {
    font-size: var(--font-size-xl);
  }
}

@media (min-width: 1024px) {
  .keep-reading-grid {
    grid-template-columns: repeat(4, 1fr);
  }
}
```

### Functionality
- [ ] Component renders with proper article data from WordPress API
- [ ] Responsive grid layout works on all screen sizes
- [ ] Article links navigate to correct article pages
- [ ] Images load properly with fallback to placeholder
- [ ] Component is reusable across different pages

### Design Compliance
- [ ] Matches Figma mockup layout and spacing
- [ ] Uses correct typography from globals.css
- [ ] Implements proper color scheme
- [ ] Mobile-first responsive design
- [ ] Proper hover states and interactions

### Code Quality
- [ ] TypeScript interfaces properly defined
- [ ] Components are modular and reusable
- [ ] CSS follows BEM methodology or existing patterns
- [ ] Proper error handling for missing data
- [ ] Accessibility best practices implemented

### Integration
- [ ] Works with existing `EnhancedPost` type system
- [ ] Integrates with WordPress data layer
- [ ] Can be imported and used in other components
- [ ] Doesn't break existing `KeepReadingSection` in `SectionPage`

## Additional Notes

1. **Performance**: Implement lazy loading for images below the fold
2. **SEO**: Ensure proper meta tags and structured data
3. **Analytics**: Add tracking for article clicks if needed
4. **Testing**: Include unit tests for component logic
5. **Storybook**: Create stories for different states (loading, error, various post counts)

## Files to Create/Modify
- `src/app/components/KeepReading/KeepReading.tsx` (new)
- `src/app/components/KeepReading/KeepReading.css` (new)
- `src/app/components/KeepReading/index.ts` (new)
- Update existing components to use new KeepReading component if needed

## Estimated Effort
**4-6 hours** including implementation, styling, testing, and integration.
